name: Reusable ECR Pipeline (Secure)

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      app-port:
        required: false
        default: "5050"
        type: string
    
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

permissions:
  actions: read
  contents: read
  security-events: write


jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ SAST - CodeQL (Static Code Analysis)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      # 3️⃣ Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      # 4️⃣ Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 5️⃣ Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest .

      # 6️⃣ 🔐 Trivy Scan (FAIL on HIGH/CRITICAL)
      - name: Scan Docker image with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest

      # 7️⃣ Push to ECR (only if scan passed)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest

      # 8️⃣ Run container test
      - name: Run container
        run: |
          docker run -d -p ${{ inputs.app-port }}:${{ inputs.app-port }} --name test-container \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest
          sleep 10

      # 9️⃣ Test endpoint
      - name: Test endpoint
        run: curl http://localhost:${{ inputs.app-port }}

      # 🔟 Cleanup
      - name: Stop container
        run: docker stop test-container