name: Reusable ECR Pipeline

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      app-port:
        required: false
        default: "5050"
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # AWS login
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      # ECR login
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest .

      # Push image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest

      # Run container test
      - name: Run container
        run: |
          docker run -d -p ${{ inputs.app-port }}:${{ inputs.app-port }} --name test-container \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:latest
          sleep 10

      # Test endpoint
      - name: Test endpoint
        run: curl http://localhost:${{ inputs.app-port }}

      # Cleanup
      - name: Stop container
        run: docker stop test-container